# General boiler plate code snippers

#
# The entire module
# 
module_c = """\
#include "{hname}"

#include "math.h"

{evalmethod}

{wrapper}
"""
#
# The header
#
module_header = """\
#ifndef __H_KERNEL_{0}
#define __H_KERNEL_{0}

/*
 * This file autogenerated by kerngen version p7
 * Copyright 2015 
 * Alejandro Francisco Queiruga
 * Lawrence Berkeley National Lab
 */

#include "kernel.h"

extern kernel_t kernel_{1};

#endif\
"""

#
#The standard generation formats
#
evalfmt = "void {0}_eval(int l_edge,{1})\n{{\n{2}\n}}"
arguments = "\n/*Inputs:*/\n{0},\n/*Outputs:*/\n{1}"

ptrdcl = "real_t * {0.name}"
inpdcl = "const real_t * restrict {0.name}"
outpdcl = "real_t * restrict {0.name}"


body = """
/*Declarations:*/
{0}

/*Intermediates:*/
{1}

/*Final calcs:*/
{2}
"""
